// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo4gBUH2JqPb5wuiLqxKvFSqftu-SbhU4',
    appId: '1:863187816863:web:f6dbbaac42bdd2d29c2daa',
    messagingSenderId: '863187816863',
    projectId: 'nomzy-daa7e',
    authDomain: 'nomzy-daa7e.firebaseapp.com',
    storageBucket: 'nomzy-daa7e.firebasestorage.app',
    measurementId: 'G-28Y8FLSYS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiBmNG6rDuwyO61V-_PaYxi-_Lz2AxVWo',
    appId: '1:863187816863:android:4c14d7dea8dffc319c2daa',
    messagingSenderId: '863187816863',
    projectId: 'nomzy-daa7e',
    storageBucket: 'nomzy-daa7e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo4gBUH2JqPb5wuiLqxKvFSqftu-SbhU4',
    appId: '1:863187816863:web:792a4ea643ec28339c2daa',
    messagingSenderId: '863187816863',
    projectId: 'nomzy-daa7e',
    authDomain: 'nomzy-daa7e.firebaseapp.com',
    storageBucket: 'nomzy-daa7e.firebasestorage.app',
    measurementId: 'G-3BLB57K3CC',
  );
}
